config/routes.rb
Rails.application.routes.draw do
  post 'refresh', action: :get, controller: 'eventbrite'
  get 'index', action: :index, controller: 'eventbrite'
  get 'event_data', action: :event_data, controller: 'eventbrite'

  get 'users/new', to: 'users#new'
  get 'users/index', to: 'users#index'
  post 'users/create', to: 'users#create'

  get 'session/new', to: 'session#new'
  post 'session/create', to: 'session#create'
  post 'session/destroy', to: 'session#destroy'

  root 'eventbrite#index'
end

app/controllers/eventbrite_controller.rb
class EventbriteController < ApplicationController
  def refresh
  end

  def index
    eventbrite_events = EventbriteEvent.all.order(id: :desc)
    @first_half_events = eventbrite_events[0.. eventbrite_events.length/2]
    @second_half_events = eventbrite_events[eventbrite_events.length/2 + 1.. eventbrite_events.length - 1]

    render layout: 'eventbrite'
  end

  def event_data
  end
end

app/views/eventbrite/index.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Parallelism by HTML5 UP
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, user-scalable=no", :name => "viewport"}/
  %body.is-preload
    / Wrapper
    #wrapper
      %header#header
        .inner

          / Nav
          %nav
            %ul
              %li
                %a{:href => "#menu"} Menu
          / Menu
          %nav#menu
            %h2 Menu
            %ul
              %li
                %a{:href => "index.html"} Home
              %li
                %a{:href => "generic.html"} Ipsum veroeros
              %li
                %a{:href => "generic.html"} Tempus etiam
              %li
                %a{:href => "generic.html"} Consequat dolor
              %li
                %a{:href => "elements.html"} Elements
            .bottom-container.text-center
              - if signed_in?
                .bottom-inner.left.display-flex-vertical-center
                  Hi #{current_user.username}
                .bottom-inner.left.display-flex-vertical-center
                  = button_to 'Log Out', session_destroy_url, method: 'post', class: 'inner-button'
              - else
                .display-flex-vertical-center.max-height
                  = button_to 'Sign In', session_new_path, method: 'post', class: 'inner-button'

      / Main
      %section#main
        / Items
        .items
          .item.intro.span-2
            %h1 Parallelism
            %p
              A responsive portfolio site
              %br/
              template by HTML5 UP
          - @first_half_events.each do |event|
            %article{class: "item thumb span-#{rand(2..4)}"}
              %h2 
                = event.event_name
              %a.image{href: event.altered_image_url, style: 'width: 100%; height: 100%'}
                = image_tag(event.altered_image_url || '')
        .items
          - @second_half_events.each do |event|
            %article{class: "item thumb span-#{rand(2..4)}"}
              %h2 
                = event.event_name
              %a.image{href: event.altered_image_url, style: 'width: 100%; height: 100%;'}
                = image_tag(event.altered_image_url || '')
       
      / Footer
      %section#footer
        %section

  
  